apiVersion: v1
kind: Service
metadata:
    name: gatekeeper
    namespace: kloudstack
spec:
    selector:
        app: gatekeeper
    ports:
        - protocol: TCP
          name: api
          port: 443
          targetPort: 443
