apiVersion: v1
kind: Service
metadata:
    labels:
        k8s-app: metric-exporter
    name: metric-exporter
    namespace: kloudstack
spec:
    selector:
        k8s-app: metric-exporter
    ports:
        - name: metrics
          port: 9476
          protocol: TCP
          targetPort: 9476
