apiVersion: v1
kind: Service
metadata:
    labels:
        k8s-app: kloudstack-metric-exporter
    name: kloudstack-metric-exporter
    namespace: hicompute
spec:
    selector:
        k8s-app: kloudstack-metric-exporter
    ports:
        - name: metrics
          port: 9476
          protocol: TCP
          targetPort: 9476
